### ISSUE TITLE
CITATIONS.cff

### ISSUE THREAD

**Issue by mike-audi** [tiki/.github#15]
because funny.

**Comment by timoguin** [comment]
Looks like it actually has more relevant use than I realized:

https://citation-file-format.github.io/

> CITATION.cff files are plain text files with human- and machine-readable citation information for software (and datasets). Code developers can include them in their repositories to let others know how to correctly cite their software.

Example:

```
cff-version: 1.2.0
message: "If you use this software, please cite it as below."
authors:
  - family-names: Druskat
    given-names: Stephan
    orcid: https://orcid.org/0000-0003-4925-7248
title: "My Research Software"
version: 2.0.4
doi: 10.5281/zenodo.1234
date-released: 2021-08-11
```
